
    create table auditoria (
        data_hora timestamp(6) not null,
        id bigint generated by default as identity,
        id_entidade_afetada bigint,
        tipo_evento varchar(50) not null check (tipo_evento in ('LOGIN','LOGOUT','CADASTRO_PRODUTO','UPDATE_PRECO','UPDATE_ESTOQUE','DELETE_PRODUTO','ERRO_SISTEMA','VENDA_REALIZADA','INFO')),
        entidade_afetada varchar(100),
        usuario_responsavel varchar(150),
        mensagem TEXT,
        primary key (id)
    );

    create table cliente (
        ativo boolean not null,
        limite_credito numeric(15,2),
        data_cadastro timestamp(6),
        id bigint generated by default as identity,
        tipo_pessoa varchar(10),
        documento varchar(14) not null unique,
        telefone varchar(20),
        inscricao_estadual varchar(50),
        nome varchar(150) not null,
        nome_fantasia varchar(150),
        endereco varchar(255),
        primary key (id)
    );

    create table cliente_aud (
        ativo boolean,
        limite_credito numeric(15,2),
        rev integer not null,
        revtype smallint,
        data_cadastro timestamp(6),
        id bigint not null,
        tipo_pessoa varchar(10),
        documento varchar(14),
        telefone varchar(20),
        inscricao_estadual varchar(50),
        nome varchar(150),
        nome_fantasia varchar(150),
        endereco varchar(255),
        primary key (rev, id)
    );

    create table fornecedores (
        ativo boolean not null,
        uf varchar(2),
        data_cadastro timestamp(6),
        id bigint generated by default as identity,
        cep varchar(10),
        cnpj varchar(18) not null unique,
        numero varchar(20),
        telefone varchar(20),
        inscricao_estadual varchar(50),
        bairro varchar(100),
        cidade varchar(100),
        contato varchar(100),
        email varchar(150),
        nome_fantasia varchar(150) not null,
        razao_social varchar(150) not null,
        logradouro varchar(255),
        primary key (id)
    );

    create table fornecedores_aud (
        ativo boolean,
        rev integer not null,
        revtype smallint,
        uf varchar(2),
        data_cadastro timestamp(6),
        id bigint not null,
        cep varchar(10),
        cnpj varchar(18),
        numero varchar(20),
        telefone varchar(20),
        inscricao_estadual varchar(50),
        bairro varchar(100),
        cidade varchar(100),
        contato varchar(100),
        email varchar(150),
        nome_fantasia varchar(150),
        razao_social varchar(150),
        logradouro varchar(255),
        primary key (rev, id)
    );

    create table item_pedido_compra_aud (
        aliquota_origem numeric(38,2),
        custo_final_unitario numeric(38,2),
        mva_aplicada numeric(38,2),
        preco_unitario_tabela numeric(38,2),
        quantidade numeric(38,2),
        rev integer not null,
        revtype smallint,
        valor_icms_st numeric(38,2),
        id bigint not null,
        pedido_compra_id bigint,
        produto_id bigint,
        primary key (rev, id)
    );

    create table item_pedido_compra (
        aliquota_origem numeric(38,2),
        custo_final_unitario numeric(38,2),
        mva_aplicada numeric(38,2),
        preco_unitario_tabela numeric(38,2),
        quantidade numeric(38,2),
        valor_icms_st numeric(38,2),
        id bigint generated by default as identity,
        pedido_compra_id bigint,
        produto_id bigint,
        primary key (id)
    );

    create table lote_produto (
        ativo boolean,
        data_fabricacao date,
        data_validade date not null,
        preco_custo numeric(10,2),
        quantidade_atual numeric(10,4) not null,
        quantidade_inicial numeric(10,4),
        id bigint generated by default as identity,
        produto_id bigint not null,
        numero_lote varchar(255) not null,
        primary key (id)
    );

    create table lote_produto_aud (
        ativo boolean,
        data_fabricacao date,
        data_validade date,
        preco_custo numeric(10,2),
        quantidade_atual numeric(10,4),
        quantidade_inicial numeric(10,4),
        rev integer not null,
        revtype smallint,
        id bigint not null,
        produto_id bigint,
        numero_lote varchar(255),
        primary key (rev, id)
    );

    create table movimentacao_caixa (
        valor numeric(10,2) not null,
        caixa_id bigint not null,
        data_hora timestamp(6) not null,
        id bigint generated by default as identity,
        forma_pagamento varchar(255) check (forma_pagamento in ('DINHEIRO','PIX','CREDITO','DEBITO','CARTAO_CREDITO','CARTAO_DEBITO','CREDIARIO','BOLETO')),
        motivo varchar(255) not null,
        tipo varchar(255) not null check (tipo in ('SANGRIA','SUPRIMENTO','ENTRADA','SAIDA')),
        usuario_responsavel varchar(255),
        primary key (id)
    );

    create table movimentacao_caixa_aud (
        rev integer not null,
        revtype smallint,
        valor numeric(10,2),
        caixa_id bigint,
        data_hora timestamp(6),
        id bigint not null,
        forma_pagamento varchar(255) check (forma_pagamento in ('DINHEIRO','PIX','CREDITO','DEBITO','CARTAO_CREDITO','CARTAO_DEBITO','CREDIARIO','BOLETO')),
        motivo varchar(255),
        tipo varchar(255) check (tipo in ('SANGRIA','SUPRIMENTO','ENTRADA','SAIDA')),
        usuario_responsavel varchar(255),
        primary key (rev, id)
    );

    create table movimento_estoque (
        custo_movimentado numeric(10,4),
        movimentacao_fiscal boolean,
        quantidade_movimentada numeric(10,4),
        saldo_anterior integer,
        saldo_atual integer,
        data_movimento timestamp(6) not null,
        fornecedor_id bigint,
        id bigint generated by default as identity,
        produto_id bigint not null,
        usuario_id bigint,
        documento_referencia varchar(255),
        motivo_movimentacao varchar(255) not null check (motivo_movimentacao in ('COMPRA_SEM_NOTA_FISCAL','COMPRA_COM_NOTA_FISCAL','DEVOLUCAO_CLIENTE','CANCELAMENTO_DE_VENDA','AJUSTE_SOBRA','ESTOQUE_INICIAL','AJUSTE_ENTRADA','AJUSTE_INVENTARIO_ENTRADA','VENDA','DEVOLUCAO_AO_FORNECEDOR','AJUSTE_PERDA','PERDA_OU_QUEBRA','AJUSTE_AVARIA','USO_INTERNO','AJUSTE_SAIDA','AJUSTE_INVENTARIO_SAIDA')),
        observacao TEXT,
        tipo_movimento varchar(255) not null check (tipo_movimento in ('ENTRADA','SAIDA')),
        primary key (id)
    );

    create table pedido_compra (
        total_final numeric(15,2),
        total_impostos_estimados numeric(15,2),
        total_produtos numeric(15,2),
        uf_destino varchar(2),
        uf_origem varchar(2),
        data_criacao timestamp(6) not null,
        fornecedor_id bigint,
        id bigint generated by default as identity,
        status varchar(50) check (status in ('EM_COTACAO','APROVADO','CANCELADO','CONCLUIDO')),
        fornecedor_nome varchar(150),
        primary key (id)
    );

    create table pedido_compra_aud (
        rev integer not null,
        revtype smallint,
        total_final numeric(15,2),
        total_impostos_estimados numeric(15,2),
        total_produtos numeric(15,2),
        uf_destino varchar(2),
        uf_origem varchar(2),
        data_criacao timestamp(6),
        fornecedor_id bigint,
        id bigint not null,
        status varchar(50) check (status in ('EM_COTACAO','APROVADO','CANCELADO','CONCLUIDO')),
        fornecedor_nome varchar(150),
        primary key (rev, id)
    );

    create table produto (
        ativo boolean not null,
        data_ultima_venda date,
        dias_para_reposicao integer,
        estoque_fiscal integer,
        estoque_minimo integer,
        estoque_nao_fiscal integer,
        is_imposto_seletivo boolean,
        is_monofasico boolean,
        preco_custo numeric(15,4),
        preco_medio_ponderado numeric(15,4),
        preco_venda numeric(15,4),
        quantidade_em_estoque integer,
        revisao_pendente boolean,
        validade date,
        venda_media_diaria numeric(10,4),
        data_atualizacao timestamp(6),
        data_cadastro timestamp(6),
        fornecedor_id bigint,
        id bigint generated by default as identity,
        cfop varchar(10),
        cst varchar(10),
        unidade varchar(10),
        cest varchar(20),
        ncm varchar(20),
        classificacao_reforma varchar(50) check (classificacao_reforma in ('PADRAO','REDUZIDA_60','REDUZIDA_30','CESTA_BASICA','IMPOSTO_SELETIVO','IMUNE')),
        codigo_barras varchar(50) unique,
        origem varchar(50),
        sku varchar(50) unique,
        categoria varchar(100),
        lote varchar(100),
        marca varchar(100),
        subcategoria varchar(100),
        descricao TEXT,
        url_imagem TEXT,
        primary key (id)
    );

    create table produto_aud (
        ativo boolean,
        data_ultima_venda date,
        dias_para_reposicao integer,
        estoque_fiscal integer,
        estoque_minimo integer,
        estoque_nao_fiscal integer,
        is_imposto_seletivo boolean,
        is_monofasico boolean,
        preco_custo numeric(15,4),
        preco_medio_ponderado numeric(15,4),
        preco_venda numeric(15,4),
        quantidade_em_estoque integer,
        rev integer not null,
        revisao_pendente boolean,
        revtype smallint,
        validade date,
        venda_media_diaria numeric(10,4),
        data_atualizacao timestamp(6),
        data_cadastro timestamp(6),
        fornecedor_id bigint,
        id bigint not null,
        cfop varchar(10),
        cst varchar(10),
        unidade varchar(10),
        cest varchar(20),
        ncm varchar(20),
        classificacao_reforma varchar(50) check (classificacao_reforma in ('PADRAO','REDUZIDA_60','REDUZIDA_30','CESTA_BASICA','IMPOSTO_SELETIVO','IMUNE')),
        codigo_barras varchar(50),
        origem varchar(50),
        sku varchar(50),
        categoria varchar(100),
        lote varchar(100),
        marca varchar(100),
        subcategoria varchar(100),
        descricao TEXT,
        url_imagem TEXT,
        primary key (rev, id)
    );

    create table produto_fornecedor (
        fornecedor_id bigint not null,
        id bigint generated by default as identity,
        produto_id bigint not null,
        codigo_no_fornecedor varchar(100) not null,
        primary key (id),
        unique (fornecedor_id, codigo_no_fornecedor)
    );

    create table regra_tributaria (
        aliquota_cbs numeric(10,4) not null,
        aliquota_ibs numeric(10,4) not null,
        ano_referencia integer not null,
        data_fim date not null,
        data_inicio date not null,
        fator_reducao_antigo numeric(10,4) not null,
        id bigint generated by default as identity,
        primary key (id)
    );

    create table revinfo_custom (
        id integer generated by default as identity,
        timestamp bigint not null,
        usuario_responsavel varchar(255),
        primary key (id)
    );

    create table sugestao_preco (
        custo_base numeric(38,2),
        margem_atual_percentual numeric(38,2),
        margem_sugerida_percentual numeric(38,2),
        preco_venda_atual numeric(38,2),
        preco_venda_sugerido numeric(38,2),
        data_aprovacao timestamp(6),
        data_sugestao timestamp(6),
        id bigint generated by default as identity,
        produto_id bigint not null,
        status_precificacao varchar(50) check (status_precificacao in ('PENDENTE','REJEITADO','APROVADO')),
        observacao TEXT,
        primary key (id)
    );

    create table tb_caixa_diario (
        diferenca_caixa numeric(15,2),
        saldo_atual numeric(15,2),
        saldo_esperado_sistema numeric(15,2),
        saldo_inicial numeric(15,2),
        total_entradas numeric(15,2),
        total_saidas numeric(15,2),
        total_vendas_cartao numeric(15,2),
        total_vendas_credito numeric(15,2),
        total_vendas_debito numeric(15,2),
        total_vendas_dinheiro numeric(15,2),
        total_vendas_pix numeric(15,2),
        valor_fisico_informado numeric(15,2),
        data_abertura timestamp(6),
        data_fechamento timestamp(6),
        id bigint generated by default as identity,
        usuario_abertura_id bigint,
        status varchar(20) check (status in ('ABERTO','FECHADO')),
        analise_auditoria_ia TEXT,
        justificativa_diferenca TEXT,
        observacoes TEXT,
        primary key (id)
    );

    create table tb_caixa_diario_aud (
        diferenca_caixa numeric(15,2),
        rev integer not null,
        revtype smallint,
        saldo_atual numeric(15,2),
        saldo_esperado_sistema numeric(15,2),
        saldo_inicial numeric(15,2),
        total_entradas numeric(15,2),
        total_saidas numeric(15,2),
        total_vendas_cartao numeric(15,2),
        total_vendas_credito numeric(15,2),
        total_vendas_debito numeric(15,2),
        total_vendas_dinheiro numeric(15,2),
        total_vendas_pix numeric(15,2),
        valor_fisico_informado numeric(15,2),
        data_abertura timestamp(6),
        data_fechamento timestamp(6),
        id bigint not null,
        usuario_abertura_id bigint,
        status varchar(20) check (status in ('ABERTO','FECHADO')),
        analise_auditoria_ia TEXT,
        justificativa_diferenca TEXT,
        observacoes TEXT,
        primary key (rev, id)
    );

    create table tb_configuracao (
        aceita_crediario boolean,
        aceita_credito boolean,
        aceita_debito boolean,
        aceita_dinheiro boolean,
        aceita_pix boolean,
        agrupar_itens boolean,
        alerta_sangria numeric(15,2),
        aliquota_interna numeric(10,4),
        auto_enter_scanner boolean,
        backup_auto boolean,
        backup_hora time(6),
        backup_nuvem boolean,
        bloquear_abaixo_custo boolean,
        bloquear_estoque boolean,
        bloqueio_fora_horario boolean,
        comissao_produtos numeric(15,2),
        comissao_servicos numeric(15,2),
        desc_caixa numeric(15,2),
        desc_extra_pix boolean,
        desc_gerente numeric(15,2),
        descontar_taxas_cartao boolean,
        dias_carencia integer,
        enviar_xml_automatico boolean,
        fechamento_cego boolean,
        fidelidade_ativa boolean,
        fundo_troco_padrao numeric(15,2),
        horario_abre time(6),
        horario_fecha time(6),
        impressao_auto boolean,
        imprimir_logo_cupom boolean,
        imprimir_ticket_troca boolean,
        imprimir_vendedor boolean,
        is_matriz boolean,
        juros_mensal numeric(10,2),
        meta_diaria numeric(15,2),
        meta_mensal numeric(15,2),
        modo_contingencia boolean,
        multa_atraso numeric(10,2),
        nfe_homologacao integer,
        nfe_producao integer,
        percentual_geral numeric(5,2),
        pontos_por_real numeric(15,2),
        priorizar_monofasico boolean,
        senha_gerente_cancelamento boolean,
        serie_homologacao integer,
        serie_producao integer,
        taxa_credito numeric(10,2),
        taxa_debito numeric(10,2),
        taxa_entrega_padrao numeric(15,2),
        tempo_entrega_min integer,
        tolerancia_minutos integer,
        uf varchar(2),
        usar_balanca boolean,
        id bigint generated by default as identity,
        cep varchar(10),
        cnpj varchar(18),
        ambiente varchar(20),
        cnae varchar(20),
        comissionar_sobre varchar(20),
        cor_destaque varchar(20),
        largura_papel varchar(20),
        numero varchar(20),
        regime varchar(20),
        telefone varchar(20),
        tipo_calculo varchar(20),
        whatsapp varchar(20),
        csc_id_homologacao varchar(50),
        csc_id_producao varchar(50),
        csrt_id varchar(50),
        ie varchar(50),
        im varchar(50),
        pix_tipo varchar(50),
        tema varchar(50),
        bairro varchar(100),
        cidade varchar(100),
        complemento varchar(100),
        instagram varchar(100),
        nome_terminal varchar(100),
        token_homologacao varchar(100),
        token_producao varchar(100),
        email varchar(150),
        nome_fantasia varchar(150),
        razao_social varchar(150),
        site varchar(150),
        csrt_hash varchar(500),
        obs_padrao_cupom varchar(500),
        rodape varchar(500),
        senha_cert varchar(500),
        caminho_certificado varchar(255),
        comportamento_cpf varchar(255),
        email_contabil varchar(255),
        ibpt_token varchar(255),
        layout_cupom varchar(255),
        logo_url TEXT,
        logradouro varchar(255),
        natureza_padrao varchar(255),
        pix_chave varchar(255),
        slogan varchar(255),
        arquivo_certificado bytea,
        primary key (id)
    );

    create table tb_contas_pagar (
        data_emissao date,
        data_pagamento date,
        data_vencimento date,
        valor_pago numeric(15,2),
        valor_total numeric(15,2),
        fornecedor_id bigint,
        id bigint generated by default as identity,
        status varchar(50) check (status in ('PENDENTE','PAGO','PARCIAL','VENCIDA','CANCELADA')),
        descricao varchar(255),
        primary key (id)
    );

    create table tb_contas_receber (
        data_emissao date,
        data_pagamento date,
        data_vencimento date,
        valor_pago numeric(15,2),
        valor_total numeric(15,2),
        cliente_id bigint,
        id bigint generated by default as identity,
        venda_id bigint,
        status varchar(50) check (status in ('PENDENTE','PAGO','PARCIAL','VENCIDA','CANCELADA')),
        primary key (id)
    );

    create table tb_ibpt (
        estadual numeric(38,2),
        importado numeric(38,2),
        municipal numeric(38,2),
        nacional numeric(38,2),
        codigo varchar(255) not null,
        descricao varchar(255),
        versao varchar(255),
        primary key (codigo)
    );

    create table tb_insight_ia (
        resolvido boolean not null,
        data_geracao timestamp(6),
        id bigint generated by default as identity,
        acao_sugerida TEXT,
        criticidade varchar(255),
        mensagem TEXT,
        tipo varchar(255),
        titulo varchar(255),
        primary key (id)
    );

    create table tb_interacao_crm (
        cliente_id bigint not null,
        data_contato timestamp(6) not null,
        id bigint generated by default as identity,
        usuario_id bigint not null,
        observacao varchar(500),
        resultado varchar(255) not null,
        tipo_abordagem varchar(255) not null,
        primary key (id)
    );

    create table tb_item_venda (
        aliquota_cbs_aplicada numeric(38,2),
        aliquota_ibs_aplicada numeric(38,2),
        cfop varchar(4),
        csosn varchar(4),
        custo_unitario_historico numeric(38,2),
        desconto numeric(38,2),
        preco_unitario numeric(38,2),
        quantidade numeric(38,2),
        id bigint generated by default as identity,
        produto_id bigint,
        venda_id bigint,
        influenciaia varchar(20) check (influenciaia in ('NENHUMA','DIRETA','INDIRETA')),
        natureza_operacao varchar(100),
        primary key (id)
    );

    create table tb_item_venda_aud (
        aliquota_cbs_aplicada numeric(38,2),
        aliquota_ibs_aplicada numeric(38,2),
        cfop varchar(4),
        csosn varchar(4),
        custo_unitario_historico numeric(38,2),
        desconto numeric(38,2),
        preco_unitario numeric(38,2),
        quantidade numeric(38,2),
        rev integer not null,
        revtype smallint,
        id bigint not null,
        produto_id bigint,
        venda_id bigint,
        influenciaia varchar(20) check (influenciaia in ('NENHUMA','DIRETA','INDIRETA')),
        natureza_operacao varchar(100),
        primary key (rev, id)
    );

    create table tb_pagamento_venda (
        parcelas integer,
        valor numeric(38,2),
        id bigint generated by default as identity,
        venda_id bigint,
        forma_pagamento varchar(255) check (forma_pagamento in ('DINHEIRO','PIX','CREDITO','DEBITO','CARTAO_CREDITO','CARTAO_DEBITO','CREDIARIO','BOLETO')),
        primary key (id)
    );

    create table tb_pagamento_venda_aud (
        parcelas integer,
        rev integer not null,
        revtype smallint,
        valor numeric(38,2),
        id bigint not null,
        venda_id bigint,
        forma_pagamento varchar(255) check (forma_pagamento in ('DINHEIRO','PIX','CREDITO','DEBITO','CARTAO_CREDITO','CARTAO_DEBITO','CREDIARIO','BOLETO')),
        primary key (rev, id)
    );

    create table tb_venda (
        custo_total numeric(15,2),
        desconto_total numeric(15,2),
        quantidade_parcelas integer,
        troco numeric(15,2),
        valor_cbs numeric(15,2),
        valor_ibs numeric(15,2),
        valor_is numeric(15,2),
        valor_liquido numeric(15,2),
        valor_total numeric(15,2),
        data_autorizacao timestamp(6),
        data_venda timestamp(6),
        id_caixa bigint,
        id_cliente bigint,
        id_venda bigint generated by default as identity,
        usuario_id bigint,
        cliente_documento varchar(20),
        cliente_telefone varchar(20),
        protocolo_autorizacao varchar(20),
        canal_origem varchar(50) check (canal_origem in ('LOJA_FISICA','WHATSAPP','INSTAGRAM','GOOGLE_MAPS','E_COMMERCE','OUTROS')),
        chave_acesso_nfce varchar(50),
        forma_de_pagamento varchar(50) check (forma_de_pagamento in ('DINHEIRO','PIX','CREDITO','DEBITO','CARTAO_CREDITO','CARTAO_DEBITO','CREDIARIO','BOLETO')),
        status_nfce varchar(50) check (status_nfce in ('PENDENTE','EM_PROCESSAMENTO','AUTORIZADA','REJEITADA','CANCELADA','CONTINGENCIA_OFFLINE','ERRO_EMISSAO')),
        cliente_nome varchar(100),
        mensagem_rejeicao TEXT,
        motivo_do_cancelamento varchar(255),
        observacao TEXT,
        xml_nota TEXT,
        primary key (id_venda)
    );

    create table tb_venda_aud (
        custo_total numeric(15,2),
        desconto_total numeric(15,2),
        quantidade_parcelas integer,
        rev integer not null,
        revtype smallint,
        troco numeric(15,2),
        valor_cbs numeric(15,2),
        valor_ibs numeric(15,2),
        valor_is numeric(15,2),
        valor_liquido numeric(15,2),
        valor_total numeric(15,2),
        data_autorizacao timestamp(6),
        data_venda timestamp(6),
        id_caixa bigint,
        id_cliente bigint,
        id_venda bigint not null,
        usuario_id bigint,
        cliente_documento varchar(20),
        cliente_telefone varchar(20),
        protocolo_autorizacao varchar(20),
        canal_origem varchar(50) check (canal_origem in ('LOJA_FISICA','WHATSAPP','INSTAGRAM','GOOGLE_MAPS','E_COMMERCE','OUTROS')),
        chave_acesso_nfce varchar(50),
        forma_de_pagamento varchar(50) check (forma_de_pagamento in ('DINHEIRO','PIX','CREDITO','DEBITO','CARTAO_CREDITO','CARTAO_DEBITO','CREDIARIO','BOLETO')),
        status_nfce varchar(50) check (status_nfce in ('PENDENTE','EM_PROCESSAMENTO','AUTORIZADA','REJEITADA','CANCELADA','CONTINGENCIA_OFFLINE','ERRO_EMISSAO')),
        cliente_nome varchar(100),
        mensagem_rejeicao TEXT,
        motivo_do_cancelamento varchar(255),
        observacao TEXT,
        xml_nota TEXT,
        primary key (rev, id_venda)
    );

    create table tb_venda_perdida (
        data_registro timestamp(6),
        id bigint generated by default as identity,
        operador varchar(255),
        produto_procurado varchar(255),
        primary key (id)
    );

    create table usuario (
        ativo boolean not null,
        id bigint generated by default as identity,
        perfil_do_usuario varchar(30) not null check (perfil_do_usuario in ('ROLE_USUARIO','ROLE_ADMIN')),
        matricula varchar(50) not null unique,
        email varchar(150) not null unique,
        nome varchar(150) not null,
        senha varchar(255) not null,
        primary key (id)
    );

    create table usuario_aud (
        ativo boolean,
        rev integer not null,
        revtype smallint,
        id bigint not null,
        perfil_do_usuario varchar(30) check (perfil_do_usuario in ('ROLE_USUARIO','ROLE_ADMIN')),
        matricula varchar(50),
        email varchar(150),
        nome varchar(150),
        senha varchar(255),
        primary key (rev, id)
    );

    create index idx_venda_data 
       on tb_venda (data_venda);

    create index idx_venda_status 
       on tb_venda (status_nfce);

    create index idx_venda_cliente 
       on tb_venda (id_cliente);

    alter table if exists cliente_aud 
       add constraint FKfwfm7s2ay0nl8i44pamu9c3o7 
       foreign key (rev) 
       references revinfo_custom;

    alter table if exists fornecedores_aud 
       add constraint FKckcfnvqdk6fbyyua50xdufh9d 
       foreign key (rev) 
       references revinfo_custom;

    alter table if exists item_pedido_compra_aud 
       add constraint FKir12gj362wufn9dbpalbik2e4 
       foreign key (rev) 
       references revinfo_custom;

    alter table if exists item_pedido_compra 
       add constraint FK5b46jhr192kuunckujy63h6vn 
       foreign key (pedido_compra_id) 
       references pedido_compra;

    alter table if exists item_pedido_compra 
       add constraint FK88q2k7kb91yox7d0a4twskqh9 
       foreign key (produto_id) 
       references produto;

    alter table if exists lote_produto 
       add constraint FKblyio3lju96l70tayceknjvpx 
       foreign key (produto_id) 
       references produto;

    alter table if exists lote_produto_aud 
       add constraint FKb4w8ltw0trkiql7e97jpv2n5t 
       foreign key (rev) 
       references revinfo_custom;

    alter table if exists movimentacao_caixa 
       add constraint FKontk2lsetyoop92oitfumgx2b 
       foreign key (caixa_id) 
       references tb_caixa_diario;

    alter table if exists movimentacao_caixa_aud 
       add constraint FKfg4nua29bw6u2uvldcb2was4l 
       foreign key (rev) 
       references revinfo_custom;

    alter table if exists movimento_estoque 
       add constraint FKi89oqqv7do0p62wmk4i4qfv2o 
       foreign key (fornecedor_id) 
       references fornecedores;

    alter table if exists movimento_estoque 
       add constraint FKagvcca9ua9b9ycl07cdo9fqbx 
       foreign key (produto_id) 
       references produto;

    alter table if exists movimento_estoque 
       add constraint FKp7mw8ta60dmy05ul33ixg6pnm 
       foreign key (usuario_id) 
       references usuario;

    alter table if exists pedido_compra 
       add constraint FK37xfpipttucdtyfjcteg7b941 
       foreign key (fornecedor_id) 
       references fornecedores;

    alter table if exists pedido_compra_aud 
       add constraint FK36hk1tgagbrpl8aics1oqiekc 
       foreign key (rev) 
       references revinfo_custom;

    alter table if exists produto 
       add constraint FKpywatk7h56ms3qt6cyjtlvd3w 
       foreign key (fornecedor_id) 
       references fornecedores;

    alter table if exists produto_aud 
       add constraint FKt56fmh3ujeckj5pjq9cyh93s3 
       foreign key (rev) 
       references revinfo_custom;

    alter table if exists produto_fornecedor 
       add constraint FKedy09vprvhd5xfu8tx4bh04pg 
       foreign key (fornecedor_id) 
       references fornecedores;

    alter table if exists produto_fornecedor 
       add constraint FKjndqo3rv2gc9bsttkvcet0y98 
       foreign key (produto_id) 
       references produto;

    alter table if exists sugestao_preco 
       add constraint FKbx9lejbcn10qf0px2mninppva 
       foreign key (produto_id) 
       references produto;

    alter table if exists tb_caixa_diario 
       add constraint FKcgw39gfyfp0ye41nu8k5gy23f 
       foreign key (usuario_abertura_id) 
       references usuario;

    alter table if exists tb_caixa_diario_aud 
       add constraint FKlnm9d8fxsqjgbqyekou4x1rgu 
       foreign key (rev) 
       references revinfo_custom;

    alter table if exists tb_contas_pagar 
       add constraint FKpapjq2m9uki8xud2mar67k3mx 
       foreign key (fornecedor_id) 
       references fornecedores;

    alter table if exists tb_contas_receber 
       add constraint FKatjprveavjnsvq2i687ilq403 
       foreign key (cliente_id) 
       references cliente;

    alter table if exists tb_contas_receber 
       add constraint FK5j09uhejj07w3e4om9tjpcw80 
       foreign key (venda_id) 
       references tb_venda;

    alter table if exists tb_interacao_crm 
       add constraint FK8cq3ugymcsof0px08rpdxw6f2 
       foreign key (cliente_id) 
       references cliente;

    alter table if exists tb_interacao_crm 
       add constraint FKqu9ckot6aoav4iwx0yih3hdd0 
       foreign key (usuario_id) 
       references usuario;

    alter table if exists tb_item_venda 
       add constraint FK27civdh1532iuku4lnfr204y7 
       foreign key (produto_id) 
       references produto;

    alter table if exists tb_item_venda 
       add constraint FK2t3vwgfkq33aw2pjn89u8557d 
       foreign key (venda_id) 
       references tb_venda;

    alter table if exists tb_item_venda_aud 
       add constraint FKdbwkxq5bu78vxyd9ivtximish 
       foreign key (rev) 
       references revinfo_custom;

    alter table if exists tb_pagamento_venda 
       add constraint FKlvglo42lurhadxscf2om9pu2w 
       foreign key (venda_id) 
       references tb_venda;

    alter table if exists tb_pagamento_venda_aud 
       add constraint FKr0rs01voduggqyr4r8pgd9inh 
       foreign key (rev) 
       references revinfo_custom;

    alter table if exists tb_venda 
       add constraint FK7h4yqek28775v1f5sx8xu9uih 
       foreign key (id_caixa) 
       references tb_caixa_diario;

    alter table if exists tb_venda 
       add constraint FKnw5edqq3t1h2pdn8hc2sl7rmo 
       foreign key (id_cliente) 
       references cliente;

    alter table if exists tb_venda 
       add constraint FKcm153d6q54mq9qtpy3ug00a5d 
       foreign key (usuario_id) 
       references usuario;

    alter table if exists tb_venda_aud 
       add constraint FK946gwk3t6b8cmtyr4bd3gh86r 
       foreign key (rev) 
       references revinfo_custom;

    alter table if exists usuario_aud 
       add constraint FK4oyth77n0frohykmdx5cc0619 
       foreign key (rev) 
       references revinfo_custom;
